spring:
  application:
    name: service-system
  profiles:
    active: dev
  # 约束文件上传大小
  servlet.multipart.max-file-size: 10MB
  servlet.multipart.max-request-size: 100MB

jwt:
  # 设置jwt签名加密时使用的秘钥
  secret-key: yuyang
  # 设置jwt过期时间
  ttl: 259200000
  # 设置前端传递过来的令牌名称
  token-name: Authorization

oss:
  accessKey: xpquCtc-v1t-M3wY3b8WVCVACS1viMpUNY6aZPzg
  secretKey: 1h-V_vCrOt2UIoHf4x_Rj4GxfjsW_IINRz0VyzFQ
  bucket: thrive
  # 目录白名单
  dirList: [ "default","article","swiper" ]

# API文档配置
knife4j:
  enable: true

  # 自定义主页内容
  openapi:
    title: ThriveX 在线API文档
    description: 有些梦虽然遥不可及，但并不是不可能实现!
    email: liuyuyang1024@yeah.net
    concat: 刘宇阳
    url: https://blog.liuyuyang.net
    version: v4.0
    license: Apache 2.0
    terms-of-service-url: https://stackoverflow.com/

    # 分组
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - liuyuyang.net

  # 自定义页脚内容
  setting:
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 互联网从不缺乏天才，而努力才是最终的入场劵!