server:
  port: 9003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ThriveX?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: liuyuyang

lyy:
  email:
    host: smtp.qq.com
    port: 465
    username: 你的邮箱账号
    password: 你的邮箱授权码

  oss:
    accessKey: 七牛云的accessKey
    secretKey: 七牛云的secretKey
    bucket: thrive
