server:
  port: 9003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ThriveX?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: liuyuyang

lyy:
  email:
    host: smtp.qq.com
    port: 465
    username: 3311118881@qq.com
    password: eqtimtwkhsqhcjdi

  oss:
    accessKey: YlsypGvYxub6VtxlY3S5BrbjEL8VUwbsoDU0szu3
    secretKey: oZqTx69xoOQsazwWbM9IJLGpcJbsR5p9SURATGhH
    bucket: thrive