spring:
  application:
    name: service-system
  profiles:
    active: pro
  # 约束文件上传大小
  servlet.multipart.max-file-size: 10MB
  servlet.multipart.max-request-size: 100MB

  mail:
    default-encoding: UTF-8
    host: ${lyy.email.host}
    port: ${lyy.email.port}  # 使用 SSL 的端口
    username: ${lyy.email.username}
    password: ${lyy.email.password}
    properties:
      mail:
        smtp: # 修正拼写错误
          auth: true
          ssl:
            enable: true

logging.level.org.springframework.mail: DEBUG
logging.level.org.springframework.boot.autoconfigure.mail: DEBUG

jwt:
  # 设置jwt签名加密时使用的秘钥
  secret-key: yuyang
  # 设置jwt过期时间
  ttl: 259200000
  # 设置前端传递过来的令牌名称
  token-name: Authorization

oss:
  accessKey: ${lyy.oss.accessKey}
  secretKey: ${lyy.oss.secretKey}
  bucket: ${lyy.oss.bucket}
  # 目录白名单
  dirList:
    - default
    - article
    - record
    - swiper
    - footprint

# API文档配置
knife4j:
  enable: true

  # 自定义主页内容
  openapi:
    title: ThriveX 在线API文档
    description: 有些梦虽然遥不可及，但并不是不可能实现!
    email: liuyuyang1024@yeah.net
    concat: 刘宇阳
    url: https://liuyuyang.net
    version: v4.0
    license: Apache 2.0
    terms-of-service-url: https://stackoverflow.com/

    # 分组
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - liuyuyang.net

  # 自定义页脚内容
  setting:
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 互联网从不缺乏天才，而努力才是最终的入场劵!

dromara:
  x-file-storage: # 文件存储配置
    default-platform: local-plus-1 # 默认使用的存储平台
    thumbnail-suffix: ".min.jpg" # 缩略图后缀，例如【.min.jpg】【.png】
    # 对应平台的配置写在这里，注意缩进要对齐
    local-plus:
      - platform: local-plus # 存储平台标识
        enable-storage: true  # 启用存储
        enable-access: true # 启用访问（线上请使用 Nginx 配置，效率更高）
        domain: http://127.0.0.1:8080/file/ # 访问域名，例如：“http://127.0.0.1:8030/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: local-plus/ # 基础路径
        path-patterns: /file/** # 访问路径
        storage-path: D:/Temp/ # 存储路径
